name: release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  release-flamingo-cli:
    outputs:
      hashes: ${{ steps.slsa.outputs.hashes }}
      image_url: ${{ steps.slsa.outputs.image_url }}
      image_digest: ${{ steps.slsa.outputs.image_digest }}
    runs-on: ubuntu-latest
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Setup Go
        uses: actions/setup-go@v5.0.2
        with:
          go-version: 1.22.x
          cache: false

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Syft
        uses: anchore/sbom-action/download-syft@v0

      - name: Setup Cosign
        uses: sigstore/cosign-installer@v3

      - name: Generate release manifests
        run: |
          mkdir -p output
          echo '[CHANGELOG](https://github.com/prokress/flamingo/blob/main/CHANGELOG.md)' > output/notes.md

      - name: Save state
        id: save-state
        run: echo "{server-version}=$(cat SERVER_VERSION)" >> $GITHUB_STATE
      - name: Save Output
        id: save-output
        run: echo "{server-version}=$(cat SERVER_VERSION)" >> $GITHUB_OUTPUT

      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --release-notes=output/notes.md --skip validate --clean
          distribution: goreleaser
          version: '~> 2'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          SERVER_VERSION: ${{ steps.save-output.outputs.server-version }}
